### ISSUE TITLE
Cannot find module '/Users/xxx/ovineherd/apps/rubik/.ovine/dll_entry_assets.json'

### ISSUE THREAD

**Issue by duanshuaimin** [CareyToboo/ovine-herd#1]
运行报错，是不是还需要克隆ovine到同一个目录？

**Comment by jinmingpang** [comment]
此项目正在更新中，正在自测，预计明天会把最新代码提交上去。到时候不会有这个问题。

**Comment by duanshuaimin** [comment]
感谢！

**Comment by duanshuaimin** [comment]
可有更新？感谢！

**Comment by jinmingpang** [comment]
已经过更新代码，可以直接拉下来，试试。

**Comment by duanshuaimin** [comment]
load assetsFile: /Users/xxx/ovineherd/apps/platform/.ovine/dll_entry_assets.json with error.
 Error: Cannot find module '/Users/xxx/ovineherd/apps/platform/.ovine/dll_entry_assets.json'
Require stack:
- /Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/lib/webpack/base.js
- /Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/lib/commands/build.js
- /Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/lib/index.js
- /Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/bin/index.js
Error: Cannot find module '/Users/xxx/ovineherd/apps/platform/.ovine/dll_entry_assets.json'
Require stack:
- /Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/lib/webpack/base.js
- /Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/lib/commands/build.js
- /Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/lib/index.js
- /Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at getManifest (/Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/lib/webpack/base.js:576:33)
    at /Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/lib/webpack/base.js:663:36
    at step (/Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/lib/webpack/base.js:66:23)
    at Object.throw (/Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/lib/webpack/base.js:47:53)
    at rejected (/Users/xxx/ovineherd/apps/platform/node_modules/@ovine/cli/lib/webpack/base.js:39:65)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
error Command failed with exit code 1

**Comment by duanshuaimin** [comment]
load assetsFile: /Users/xxx/ovineherd/apps/rubik/.ovine/dll_entry_assets.json with error.
 Error: Cannot find module '/Users/xxx/ovineherd/apps/rubik/.ovine/dll_entry_assets.json'
Require stack:
- /Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/lib/webpack/base.js
- /Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/lib/commands/build.js
- /Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/lib/index.js
- /Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/bin/index.js
Error: Cannot find module '/Users/xxx/ovineherd/apps/rubik/.ovine/dll_entry_assets.json'
Require stack:
- /Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/lib/webpack/base.js
- /Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/lib/commands/build.js
- /Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/lib/index.js
- /Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at getManifest (/Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/lib/webpack/base.js:576:33)
    at /Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/lib/webpack/base.js:663:36
    at step (/Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/lib/webpack/base.js:66:23)
    at Object.throw (/Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/lib/webpack/base.js:47:53)
    at rejected (/Users/xxx/ovineherd/apps/rubik/node_modules/@ovine/cli/lib/webpack/base.js:39:65)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
